version: '3.8'

services:
  flask-app:
    image: vladim1rzolotarev/flask-app:latest
    build:
      context: .
    expose:
      - "5000"
    depends_on:
      - fluentd
    environment:
      - FLASK_ENV=production
    restart: always
    networks:
      - my_network
    deploy:
      replicas: 3
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: flask.logs
    links:
      - fluentd

  nginx:
    image: nginx:7777
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "2727:80"
    depends_on:
      - fluentd
      - flask-app
    networks:
      - my_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.logs
    links:
      - fluentd

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - my_network
    volumes:
      - grafana_data:/var/lib/grafana

  fluentd:
    image: fluent/fluentd:latest
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
      - fluentd_data:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
    networks:
      - my_network

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    ports:
      - "3100:3100"
    depends_on:
      - fluentd
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  grafana_data:
  fluentd_data:
  loki_data:
