services:
  flask-app:
    image: vladim1rzolotarev/flask-app:latest
    build:
      context: .
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    networks:
      - my_network
    deploy:
      replicas: 1
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "job=flask-app,container_name={{.Name}}"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app
      - grafana # Добавляем зависимость от Grafana
    networks:
      - my_network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "job=nginx,container_name={{.Name}}"
        loki-pipeline-stages: |
          - json:
              expressions:
                remote_addr:
                request:
                status:
          - labels:
              status:
          - static_labels:
              app: nginx

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=https://zolotarev.tech/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    expose:
      - "3000"
    networks:
      - my_network
    volumes:
      - grafana_data:/var/lib/grafana
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "job=grafana"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "job=prometheus"

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    ports:
      - "3100:3100"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  grafana_data:
  loki_data:
