#start

services:
  flask-app:
    image: vladim1rzolotarev/flask-app:latest
    build:
      context: .
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    networks:
      - my_network
    deploy:
      replicas: 1
    labels:
      - "prometheus-job=flask-app"
      - "prometheus-port=5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app
    networks:
      - my_network
    labels:
      - "prometheus-job=nginx"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://nginx/basic_status'
    networks:
      - my_network
    depends_on:
      - nginx

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - my_network
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    networks:
      - my_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - alertmanager

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - my_network
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/letsencrypt/live/zolotarev.tech/fullchain.pem:/etc/grafana/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/zolotarev.tech/privkey.pem:/etc/grafana/certs/privkey.pem:ro
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/fullchain.pem
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/privkey.pem
      - GF_SERVER_DOMAIN=zolotarev.tech

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    ports:
      - "3100:3100"
    restart: always
    networks:
      - my_network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./promtail-config.yml:/etc/promtail/config.yml
    command:
      - '-config.file=/etc/promtail/config.yml'
    networks:
      - my_network
    depends_on:
      - loki

networks:
  my_network:
    driver: bridge

volumes:
  grafana_data:
  loki_data:
