services:
  flask-app:
    image: vladim1rzolotarev/flask-app:latest
    build:
      context: .
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    networks:
      - my_network
    deploy:
      replicas: 1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - my_network
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/letsencrypt/live/zolotarev.tech/fullchain.pem:/etc/grafana/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/zolotarev.tech/privkey.pem:/etc/grafana/certs/privkey.pem:ro
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/fullchain.pem
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/privkey.pem
      - GF_SERVER_DOMAIN=zolotarev.tech

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    ports:
      - "3100:3100"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  grafana_data:
  loki_data:
