auth_enabled: false

server:
  http_listen_port: 3100

ingestion:
  rate_limit: true  # Включите ограничение на скорость, если это необходимо
  burst_size: 1000  # Установите размер всплеска, если это необходимо

schema_config:
  configs:
    - from: 2023-01-01  # Убедитесь, что дата актуальна
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

limits_config:
  reject_old_samples: true  # Установите в true, если хотите отклонять старые образцы

chunk_store_config:
  max_look_back_period: 1h  # Установите на более длительный период
