auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  storage:
    filesystem:
      directory: /loki/storage  # Все данные теперь в одном месте
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks  # Добавлено хранение чанков

limits_config:
  reject_old_samples: false  # Важно для Docker-логов!
  reject_old_samples_max_age: 168h  # 7 дней
  ingestion_rate_mb: 16      # Лимит на прием логов
  ingestion_burst_size_mb: 32
  max_entries_limit_per_query: 5000
  retention_period: 168h     # Хранение 7 дней

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  retention_enabled: true

chunk_store_config:
  max_look_back_period: 168h  # Соответствует retention_period

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576  # 1MB
