version: '3.8'

services:
  flask-app:
    image: vladim1rzolotarev/flask-app:latest
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      fluentd:
        condition: service_healthy
    environment:
      - FLASK_ENV=production
    restart: always
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224
        tag: flask.logs

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "2727:80"
    depends_on:
      flask-app:
        condition: service_healthy
    networks:
      - my_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224
        tag: nginx.logs

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network

  grafana:
    image: grafana/grafana:10.1.1
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - my_network
    volumes:
      - grafana_data:/var/lib/grafana

  fluentd:
    image: fluent/fluentd:latest
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
      - fluentd_data:/fluentd/log
    ports:
      - "24224:24224"
    healthcheck:
      test: ["CMD", "sh", "-c", "echo '{\"health\": \"check\"}' | fluent-cat debug"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - my_network

  loki:
    image: grafana/loki:2.9.1
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    depends_on:
      fluentd:
        condition: service_healthy
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  grafana_data:
  fluentd_data:
  loki_data:
