name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Логин в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Сборка Docker-образа
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest .

      - name: Пуш в Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest
