name: Deploy to Staging and Production

on:
  push:
    branches:
      - feature  # Запуск деплоя на staging
      - master     # Запуск деплоя на production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
          TAG="latest"
        else
          TAG="staging"
        fi

        sudo docker build -t vladim1rzolotarev/flask-app:$TAG .
        sudo docker push vladim1rzolotarev/flask-app:$TAG

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          set -e
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            COMPOSE_FILE="docker-compose.prod.yml"
            TAG="latest"
          else
            COMPOSE_FILE="docker-compose.staging.yml"
            TAG="staging"
          fi

          echo "Pulling latest image..."
          sudo docker pull vladim1rzolotarev/flask-app:$TAG
          
          echo "Stopping current containers..."
          sudo docker-compose -f $COMPOSE_FILE down
          
          echo "Starting new containers..."
          sudo docker-compose -f $COMPOSE_FILE up -d

          echo "Checking container health..."
          sleep 10
          if ! docker ps | grep -q "flask-app"; then
            echo "Deployment failed! Triggering rollback..."
            exit 1  # Запускаем rollback
          fi

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()  # Запускается, если job deploy упал

    steps:
    - name: Rollback on failure
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "Rolling back to previous stable version..."
          
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            COMPOSE_FILE="docker-compose.prod.yml"
            TAG="latest"
          else
            COMPOSE_FILE="docker-compose.staging.yml"
            TAG="staging"
          fi
          
          # Откат на предыдущий стабильный образ
          sudo docker pull vladim1rzolotarev/flask-app:rollback
          sudo docker tag vladim1rzolotarev/flask-app:rollback vladim1rzolotarev/flask-app:$TAG
          
          sudo docker-compose -f $COMPOSE_FILE down
          sudo docker-compose -f $COMPOSE_FILE up -d
          
          echo "Rollback completed successfully."
